#!/bin/bash
# /usr/local/bin/webyonet

if [ "$EUID" -ne 0 ]; then
  echo "❌ Bu programı çalıştırmak için root (sudo) yetkisine sahip olmalısınız."
  exit 1
fi

if [[ "$1" == "-b" || "$1" == "--backup" ]]; then
  if [ -f /usr/local/bin/webyonet-bin/backup.py ]; then
    python3 /usr/local/bin/webyonet-bin/backup.py
  else
    echo "❌ /usr/local/bin/webyonet-bin/backup.py bulunamadı."
    exit 1
  fi
elif [[ "$1" == "-db" || "$1" == "--database-backup" ]]; then
  if [ -f /usr/local/bin/webyonet-bin/dbbackup.sh ]; then
    bash /usr/local/bin/webyonet-bin/dbbackup.sh
  else
    echo "❌ /usr/local/bin/webyonet-bin/dbbackup.sh bulunamadı."
    exit 1
  fi
else
  if [ -f /usr/local/bin/webyonet-bin/webyonet_menu.sh ]; then
    bash /usr/local/bin/webyonet-bin/webyonet_menu.sh
  else
    echo "❌ /usr/local/bin/webyonet-bin/webyonet_menu.sh bulunamadı."
    exit 1
  fi
fi